language: python

# The idea here is to test all supported versions of python with xcb-proto
# master, and then do some testing on older xcb-proto versions to make sure we
# don't regress. We probably don't need the full matrix, so let's save
# travis-ci some $$.
jobs:
  include:
  - python: 3.5
    env: XCBVER=master
  - python: 3.6
    env: XCBVER=master
  - python: 3.7
    env: XCBVER=master
  - python: 3.8
    env: XCBVER=master
  - python: pypy3
    env: XCBVER=master
  - python: 3.8
    env: XCBVER=xcb-proto-1.13
  - python: 3.8
    env: XCBVER=1.12
  - python: 3.8
    env: XCBVER=1.11

addons:
  apt:
    packages:
      - happy
      - alex
      - x11-apps
      - xvfb

install:
  - sudo apt-add-repository -y ppa:hvr/ghc && sudo apt update && sudo apt install cabal-install-2.4 ghc-8.6.3
  - export PATH=$PATH:/opt/cabal/bin:/opt/ghc/bin
  - cabal new-update
  - pip install -r requirements.txt
  - git clone https://gitlab.freedesktop.org/xorg/proto/xcbproto.git proto
  - ( cd proto && git checkout "$XCBVER" )

script: "make XCBDIR=$TRAVIS_BUILD_DIR/proto/src check"

os: linux
dist: xenial
