language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cabal/lib

addons:
  apt:
    packages:
      - xcb-proto
      - ghc
      - cabal-install
      - happy
      - alex
      - x11-apps
      - xvfb

install:
  - cabal update
  - cabal install --only-dependencies --enable-tests
  - cabal configure --enable-tests
  - pip install -r requirements.txt

script: "make -j3 check"

sudo: false
